name: proselint

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        version: '3.x'
    - run: pip3 install proselint
    - run: mkdir -p ~/.config/proselint && cp lecture8/proselint-config.json ~/.config/proselint/config
    - run: make proselint
